--- 
# env: 
  #Ros master uri should not be set here, it can vary per robot
  #ROS_MASTER_URI: "http://localhost:11311"
launch_configs: 
  -
    command: "mon launch sootballs_applications_robot alica_base.launch"
    monitor_node: true
    name: alica_base
  -
    command: "mon launch sootballs_applications_common bridge.launch type:=robot"
    monitor_node: true
    name: bridge_common
  -
    command: "mon launch sootballs_applications_common bridge.launch type:=rosmon"
    monitor_node: true
    name: bridge_rosmon
  -
    command: "mon launch sootballs_applications_edge dispatcher.launch"
    monitor_node: true
    name: dispatcher
  -
    command: "mon launch sootballs_applications_robot infrastructure.launch"
    monitor_node: true
    name: infrastructure
  -
    command: "mon launch sootballs_agent_joystick joystick.launch"
    monitor_node: true
    name: joystick
  -
    command: "mon launch sootballs_applications_robot localization.launch"
    monitor_node: true
    name: localization
  -
    command: "mon launch sootballs_applications_robot mapping.launch"
    monitor_node: true
    name: mapping
  -
    command: "mon launch sootballs_applications_common map_poller.launch"
    monitor_node: true
    name: map_poller
  -
    command: "mon launch sootballs_applications_edge update_map_server.launch"
    monitor_node: true
    name: map_update
  -
    command: "mon launch sootballs_applications_common map_poller.launch simulation:=false"
    monitor_node: true
    name: edge_map_poller
  -
    command: "mon launch sootballs_applications_robot navigation.launch"
    monitor_node: true
    name: navigation
  -
    command: "mon launch sootballs_applications_robot record_robot_bag.launch"
    monitor_node: true
    name: record_robot_bag
  -
    command: "mon launch sootballs_applications_robot robot_ui.launch"
    monitor_node: true
    name: robot_ui
  -
    command: "mon launch sootballs_applications_simulator simulation_server.launch use_rviz:=false"
    monitor_node: true
    name: simulator
  -
    command: "mon launch sootballs_applications_edge system_ui.launch"
    monitor_node: true
    name: system_ui
  -
    command: "mon launch sootballs_applications_robot topomap_realsense.launch"
    monitor_node: true
    name: realsense_sensor
  -
    command: "mon launch sootballs_applications_robot topomap_bag_realsense.launch"
    monitor_node: true
    name: realsense_record

launch_groups: 
  - 
    launch_configs: 
      - alica_base
      - infrastructure
      - navigation
      - localization
      - map_poller
      - bridge_common
      - bridge_rosmon
      - robot_ui
      - record_robot_bag
    name: sootball